### ISSUE TITLE
Feature request: expose playURI as a channel

### ISSUE THREAD

**Issue by thjunge11** [patrickse/org.openhab.binding.volumio2#3]
Hi @patrickse 

I have seen in your service implementation, that you prepared methods to send a playURI request to volumio. Is is a lot of effort to expose this as a channel?

My usecase: I implemented some alarm rules in openhab, which trigger volumio to play them. But if certain playlist used in the rules are deleted on volumio host (on purpose or by accident) the alarm will not go off anymore.

Are you still active on this binding. If not, I could try to add the channel handler stuff and so on by myself, but I am completely new to openhab bindings, so may take some time...

**Comment by patrickse** [comment]
😉

I will have a look this weekend.
